export const DdragonAvailableLanguages = Object.freeze({
    cs_CZ: 'cs_CZ',
    el_GR: 'el_GR',
    pl_PL: 'pl_PL',
    ro_RO: 'ro_RO',
    hu_HU: 'hu_HU',
    en_GB: 'en_GB',
    de_DE: 'de_DE',
    es_ES: 'es_ES',
    it_IT: 'it_IT',
    fr_FR: 'fr_FR',
    ja_JP: 'ja_JP',
    ko_KR: 'ko_KR',
    es_MX: 'es_MX',
    es_AR: 'es_AR',
    pt_BR: 'pt_BR',
    en_US: 'en_US',
    en_AU: 'en_AU',
    ru_RU: 'ru_RU',
    tr_TR: 'tr_TR',
    // ms_MY: 'ms_MY', // Not available, for some reason
    en_PH: 'en_PH',
    th_TH: 'th_TH',
    vi_VN: 'vi_VN',
    id_ID: 'id_ID',
    zh_MY: 'zh_MY',
    zh_CN: 'zh_CN',
    zh_TW: 'zh_TW'
});
